# Generated by Django 4.2.6 on 2023-10-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_users_userdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='Users',
        ),
    ]
