# Generated by Django 4.2.6 on 2023-10-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_userdetails_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200)),
                ('course_category', models.CharField(max_length=200)),
                ('course_image', models.ImageField(upload_to='')),
                ('course_views', models.BigIntegerField()),
            ],
        ),
    ]
